<?php

function node_slideshow_node_view($node, $view_mode, $langcode) {
    $image_path = base_path() . path_to_theme() . '/images';
    drupal_add_js(array('node_slideshow' => array('image_path' => $image_path)), 'setting');
    if (($node->type == 'home_page')) {
        $path = libraries_get_path('jquery.cycle');
        drupal_add_js($path . '/jquery.cycle.all.js');
        drupal_add_js(drupal_get_path('module', 'node_slideshow') . '/script.js');
    }
    if (($node->type == 'product')) {
        drupal_add_js(drupal_get_path('module', 'node_slideshow') . '/product.js');
    }
}

function node_slideshow_form_alter(&$form, $form_state, $form_id) {

    if (isset($form_state['view'])) {
        if ($form_state['view']->name == 'news') {

            $form['field_news_category_tid']['#options']['All'] = t('All');
        }
    }

    if ($form_id == 'views_exposed_form' && isset($form['distance'])) { //then we have the dealer locator
        /*
        $dealer = theme('image', array(
            '#src' => base_path() . path_to_theme() . '/images/dealer.png',
            '#alt' => 'Dealer Pin',
         ));
        $distributor = theme('image', array(
            '#src' => base_path() . path_to_theme() . '/images/distributor.png',
            '#alt' => 'Distributor Pin',
         ));
        
        $form['type']['#prefix'] = $dealer;
        $form['type']['#suffix'] = $distributor;
         * 
         */

        //setup textfields
        $form['distance']['postal_code']['#title'] = 'Postcode';
        $form['distance']['postal_code']['#title_display'] = 'invisible';
        $form['distance']['postal_code']['#size'] = 20;
        $form['distance']['postal_code']['#default_value'] = 'Enter Postcode';
        $form['distance']['postal_code']['#attributes']['onblur'] = "if (this.value == '') {this.value = 'Enter Postcode';}";
        $form['distance']['postal_code']['#attributes']['onfocus'] = "if (this.value == 'Enter Postcode') {this.value = '';}";
        //print_r($form['distance']['country']);
        $form['distance']['country']['#title_display'] = 'invisible';
        $form['distance']['search_distance']['#title'] = 'Within';
        $form['distance']['search_distance']['#size'] = 20;
        $form['distance']['search_units']['#options']['km'] = 'km.';
        $form['distance']['search_units']['#options']['mile'] = 'm.';
        $form['submit'] = array('#type' => 'image_button', '#src' => base_path() . path_to_theme() . '/images/buttons/go.png');
       
        $form['new_reset'] = array(
            '#type' => 'image_button', 
            '#src' => base_path() . path_to_theme() . '/images/buttons/reset.png',
            '#submit' => array('resetview'),
        );
       
        //set country options
        $form['distance']['country']['#options'] = array(
            'ar' => 'Argentina',
            'au' => 'Australia',
            'at' => 'Austria',
            'be' => 'Belgium',
            'br' => 'Brazil',
            'bg' => 'Bulgaria',
            'ca' => 'Canada',
            'cl' => 'Chile',
            'co' => 'Colombia',
            'hr' => 'Croatia',
            'cy' => 'Cyprus',
            'cz' => 'Czech Republic',
            'dk' => 'Denmark',
            'ee' => 'Estonia',
            'fi' => 'Finland',
            'fr' => 'France',
            'de' => 'Germany',
            'gr' => 'Greece',
            'hk' => 'Hong Kong',
            'hu' => 'Hungary',
            'ie' => 'Ireland',
            'it' => 'Italy',
            'jp' => 'Japan',
            'lv' => 'Latvia',
            'lt' => 'Lithaunia',
            'my' => 'Malaysia',
            'mq' => 'Martinique',
            'mx' => 'Mexico',
            'nl' => 'Netherlands',
            'nc' => 'New Caledonia',
            'nz' => 'New Zealand',
            'no' => 'Norway',
            'pe' => 'Peru',
            'ph' => 'Philippines',
            'pl' => 'Poland',
            'pt' => 'Portugal',
            'ru' => 'Russia',
            'sg' => 'Singapore',
            'si' => 'Slovenia',
            'za' =>'South Africa',
            'es' => 'Spain',
            'se' => 'Sweden',
            'ch' => 'Switzerland',
            'th' => 'Thailand',
            'tr' => 'Turkey',
            'gb' => 'UK',
            'ua' => 'Ukraine',
            'us' => 'USA',
            'vn' => 'Vietnam',
        );
        
       

    }
    
    if ($form_id == 'views_exposed_form' && $form['#id'] == 'views-exposed-form-faq-page') {
        $form['submit'] = array('#type' => 'image_button', '#src' => base_path() . path_to_theme() . '/images/buttons/go.png');
        $form['reset'] = array(
            '#type' => 'image_button', 
            '#src' => base_path() . path_to_theme() . '/images/buttons/reset.png',
            '#submit' => array('resetfaq'),
        );
    }
    
    
    

   
    if($form_id == 'user_login'){

        $form['actions']['submit'] = array('#type' => 'image_button', '#src' => base_path() . path_to_theme() . '/images/buttons/go.png');
    }
    
    if($form_id == 'views_exposed_form' && $form['#id'] == 'views-exposed-form-sail-finder-page'){
        
        
        $item = array(
          'label' => 'Where do you windsurf?',  
          'value' => 'water_state', 
        );
        $form['water_state'] = array(
            '#weight' => -1000,
            '#type' => 'radios',
            '#options' => array(
              'waves'  => 'In Waves',
              'flat'   => 'On Flat Water',
              'race'   => 'On The Racecourse',
            ),
        );
        
        $form['field_board_type_tid']['#weight'] = 10;
        $form['reset'] = array(
            '#type' => 'image_button', 
            '#src' => base_path() . path_to_theme() . '/images/buttons/reset.png',
            '#submit' => array('resetprodfinder'),
        );
   
        array_unshift($form['#info'], $item );
        
        
    }
    

}

function resetview(){
    drupal_goto('dealer-locator');
}

function resetfaq(){
    drupal_goto('faq');
}

function resetprodfinder(){
    drupal_goto('product-finder');
}

function node_slideshow_views_pre_render(&$view) {
    if ($view->name == 'sail_finder' && $view->editing == FALSE) {
        //these need to be loaded on power-slider view page
        drupal_add_js(drupal_get_path('module', 'node_slideshow') . '/power-slider.js');
        
       
    }
}