<?php

function sliders_views_pre_render(&$view)
{
    if($view->name == 'property_search' && $view->editing == FALSE)
    {
        //these need to be loaded on power-slider view page
        drupal_add_js(drupal_get_path('module', 'sliders') . '/sliders.js');
    }
}

function sliders_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'views_exposed_form'){
      
      //add better sort labels
      $form['sort_bef_combine']['#options']['created ASC'] = 'Sort: Date (Oldest First)';
      $form['sort_bef_combine']['#options']['created DESC'] = 'Sort: Date (Newest First)';
      
      $form['sort_bef_combine']['#options']['field_price_value ASC'] = 'Sort: Price (Low-High)';
      $form['sort_bef_combine']['#options']['field_price_value DESC'] = 'Sort: Price (High-Low)';
      
      $form['distance']['postal_code']['#title'] = 'Post Code';
      
      //build some update buttons
      $form['update_budget'] = array(
        '#markup' => '<input type="submit" class="update-button" value="Update Budget" />',
      );
      
      $form['update_town'] = array(
        '#markup' => '<input type="submit" class="update-button" value="Update Town" />',
      );
      
      $form['update_bedrooms'] = array(
          '#markup' => '<input type="submit" class="update-button" value="Update Bedrooms" />',
      );
      
      $form['update_features'] = array(
          '#markup' => '<input type="submit" class="update-button" value="Update Features" />',
      );
      
      $update_budget= array(
          'value' => 'update_budget',
      );
      
      $update_town = array(
          'value' => 'update_town',
      );
      
      $update_bedrooms = array(
          'value' =>'update_bedrooms',
      );
      
      $update_features = array(
          'value' => 'update_features',
      );
      
      /*
       * reset form order...
       * how to sort this is posted here:
       * http://snyderp.tumblr.com/post/12048300955/drupal-bits-programmatically-editing-and-reordering
     */  
      $property_type = $form['#info']['filter-field_property_type_tid'];
      $budget_min = $form['#info']['filter-field_price_value'];
      $budget_max = $form['#info']['filter-field_price_value_1'];
      $town = $form['#info']['filter-field_town_tid'];
      $bedrooms_min = $form['#info']['filter-field_bedrooms_value'];
      $bedrooms_max = $form['#info']['filter-field_bedrooms_value_1'];
      $features = $form['#info']['filter-field_features_tid'];
      
      //unset form
      unset($form['#info']['filter-field_property_type_tid']);
      unset($form['#info']['filter-field_price_value']);
      unset($form['#info']['filter-field_price_value_1']);
      unset($form['#info']['filter-field_town_tid']);
      unset($form['#info']['filter-field_bedrooms_value']);
      unset($form['#info']['filter-field_bedrooms_value_1']);
      unset($form['#info']['filter-field_features_tid']);
      

      //reset form IN THIS ORDER   
      $form['#info']['filter-field_property_type_tid'] = $property_type;
      $form['#info']['filter-field_price_value'] = $budget_min;
      $form['#info']['filter-field_price_value_1'] = $budget_max;
      $form['#info']['update_budget'] = $update_budget;
      $form['#info']['filter-field_town_tid'] = $town;
      $form['#info']['update_town'] = $update_town;
      $form['#info']['filter-field_bedrooms_value'] = $bedrooms_min;
      $form['#info']['filter-field_bedrooms_value_1'] = $bedrooms_max;
      $form['#info']['update_bedrooms'] = $update_bedrooms;
      
      $form['#info']['filter-field_features_tid'] = $features;
      $form['#info']['update_features'] = $update_features;
      
      $form['new_reset'] = array(
          '#type' => 'submit',
          '#value' => 'Reset All',
          '#weight' => '-2000',
          '#submit' => array('reset_property_search'),
      );
      
      //add some labels for budget
      $form['field_price_value']['#title']= '£ min';
      $form['field_price_value_1']['#title'] = '£ max';
      $form['#info']['filter-field_price_value']['label'] = 'Budget';
      $form['#info']['filter-field_price_value_1']['label'] ='';
     
      //ad some labels for bedrooms
      $form['field_bedrooms_value']['#title'] = 'Min';
      $form['field_bedrooms_value_1']['#title'] = 'Max';
      $form['#info']['filter-field_bedrooms_value']['label'] = 'Bedrooms';
      $form['#info']['filter-field_bedrooms_value_1']['label'] = '';
      
      //wrap up the between fields
/*
      $form['field_price_value']['#prefix'] = '<div class="webform-container-inline"><div class="exposed-field-wrapper">';
      $form['field_price_value']['#suffix'] = '</div>';

      $form['field_price_value_1']['#prefix'] = '<div class="exposed-field-wrapper">';
      $form['field_price_value_1']['#suffix'] = '</div></div>';
      */
  }
}


function reset_property_search(){
    
    if (isset($_GET['mode'])){
        $mode = $_GET['mode'];
        drupal_goto("property-search/property-for-sale", array('query'=>array(
            'mode' => $mode)));
    }
    else {
        drupal_goto('property-search/property-for-sale');
    }
        
}

